### ISSUE TITLE
电平转换电路简化的可能性

### ISSUE THREAD

**Issue by Maxwelltoo** [abgelehnt/Tiny-DAPLink#1]
CH552系列芯片本身是支持3.3V输入的，直接将稳压输出的3.3V接入VCC，应该就可以省去两个SN74LVC1T45DBV，去掉SWDIO_DIR引脚。
考虑到接入IO的LED和键盘功能并非必须，是否可能将这些引脚全部省下来，进一步简化电路，使用更小封装的CH552E（刚好只有10个引脚）？

**Comment by abgelehnt** [comment]
使用CH552E的话，串口引脚会和SPI引脚冲突（时序刷写用到了SPI）
如果退一步，不使用SPI加速刷写的话，使用3.3V电源输入的串口不支持115200波特率传输（16MHz主频），作为最常用的串口波特率，不支持的话整个串口功能都残废了。
